# Generated by Django 2.2.1 on 2019-05-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190519_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
